SELECT
    e.FIRST_NAME,
    d.DEPARTMENT_NAME,
    l.STREET_ADDRESS,
    l.STATE_PROVINCE,
    c.COUNTRY_NAME,
    r.REGION_NAME
    FROM HR.EMPLOYEES e
    LEFT JOIN HR.DEPARTMENTS d
    ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
    LEFT JOIN HR.LOCATIONS l
    ON d.LOCATION_ID = l.LOCATION_ID
    LEFT JOIN HR.COUNTRIES c
    ON l.COUNTRY_ID = c.COUNTRY_ID
    LEFT JOIN HR.REGIONS r
    ON c.REGION_ID = r.REGION_ID
    WHERE d.LOCATION_ID IS NOT NULL
    AND c.COUNTRY_NAME IS NOT NULL
    AND r.REGION_NAME IS NOT NULL; 