SELECT
    e.FIRST_NAME,
    e.SALARY,
    e.DEPARTMENT_ID,
    d.DEPARTMENT_NAME,
    j.JOB_TITLE
FROM HR.EMPLOYEES e
LEFT JOIN HR.DEPARTMENTS d
    ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
LEFT JOIN HR.JOBS j
    ON e.JOB_ID = j.JOB_ID
    WHERE d.DEPARTMENT_NAME IS NOT NULL;